export const ipcChannels = {
  getBootstrapState: "bootstrap:get-state",
  startTracking: "tracking:start",
  stopTracking: "tracking:stop",
  enterFlowMode: "flow:enter",
  stateUpdated: "state:updated",
  trayAction: "tray:action",
  runChromeCommand: "chrome:run-command",
  runVoiceCommand: "voice:run-command",
  transcribeAudio: "voice:transcribe",
  showWindow: "window:show",
  hideWindow: "window:hide",
  saveLayout: "layout:save",
  listLayouts: "layout:list",
  deleteLayout: "layout:delete",
  recallLayout: "layout:recall",
  analyticsWeekly: "analytics:weekly",
  licenseGet: "license:get",
  licenseActivate: "license:activate",
  licenseDeactivate: "license:deactivate",
  triggerSuggestion: "trigger:suggestion",
  capsuleSave: "capsule:save",
  capsuleList: "capsule:list",
  capsuleRestore: "capsule:restore",
  capsuleDelete: "capsule:delete",
  focusScore: "focus:score",
  focusAlert: "focus:alert"
} as const;
